# Phi3 vision vLLM inference config.
#
# Requirements:
#   - Run `pip install vllm`
#
# Usage:
#   oumi infer -i -c configs/recipes/vision/phi3/inference/vllm_infer.yaml \
#     --image "tests/testdata/images/the_great_wave_off_kanagawa.jpg"
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "allenai/MolmoE-1B-0924"
  torch_dtype_str: "auto"
  model_max_length: 32768
  chat_template: "molmo"
  trust_remote_code: True

generation:
  max_new_tokens: 64 #???
  batch_size: 1 #???

engine: VLLM
