name: oumi-ssh

num_nodes: 1

resources:
  accelerators: { "A40", "A10", "A10g", "A100-80GB-SXM", "A100", "L4" } # Some single-gpu options
  # accelerators: { "A100": 2, "L4": 4 }  # Some multi-gpu options

  disk_size: 200  # Disk size in GB
  # region: us-central1  # Uncomment this line to only consider a specific region.

  use_spot: false

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials
  /output_dir_gcs:
    source: gs://oumi-dev-us-central1
    store: gcs
    mode: MOUNT

envs:
  WANDB_PROJECT: oumi-debug

setup: |
  set -e
  pip install uv && uv pip install '.[dev]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh
