####################################################
# Training Parameters : Q-LoRA SFT of Llama3.1 70B #
####################################################

# We replicate the training parameters of:
# (1) https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/70B_lora.yaml

# Except:
# 1. We finetune the *base* Llama 3.1 model - not the already instruction-tuned one.
# 2. We apply a max sequence length of 8192.
# 3. We use the chat-ml template to preprocess the alpaca dataset.

model:
  model_name: "meta-llama/Meta-Llama-3.1-70B"
  chat_template: "chat_ml"
  model_max_length: 8192
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "yahma/alpaca-cleaned"
        shuffle: True
    target_col: "prompt"
    seed: 123

training:
  trainer_type: "TRL_SFT"
  num_train_epochs: 1
  per_device_train_batch_size: 2
  learning_rate: 3.0e-4
  warmup_steps: 100
  lr_scheduler_type: "cosine"
  optimizer: "adamw_torch_fused"
  weight_decay: 0.01
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  seed: 123
  use_peft: True
  save_steps: 1000
  logging_steps: 50
  logging_first_step: True
  log_model_summary: True
  include_performance_metrics: True
  enable_wandb: True
  trainer_kwargs:
    save_total_limit: 2

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 3

peft:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.0
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "LlamaDecoderLayer"
